### ISSUE TITLE
Problems while Running the code

### ISSUE THREAD

**Issue by chinge55** [pliang279/HighMMT#2]
As given in the documentation, I installed the dependencies and tried to run the code: 
```bash
$ python private_test_scripts/perceivers/roboticstasks.py model.pt
```
After trying to run that, it gives me some sort of ```fannypack``` related error: 

The full error is: 
```
python private_test_scripts/perceivers/roboticstasks.py model.pt
Output will be model.pt
Traceback (most recent call last):
  File "/media/4TB_hardisk/sangam/HighMMT/private_test_scripts/perceivers/roboticstasks.py", line 31, in <module>
    trains3, valid3, test3 = PushTask.get_dataloader(
  File "/media/4TB_hardisk/sangam/HighMMT/datasets/gentle_push/data_loader.py", line 84, in get_dataloader
    train_trajectories = cls.get_train_trajectories(**dataset_args)
  File "/media/4TB_hardisk/sangam/HighMMT/datasets/gentle_push/data_loader.py", line 134, in get_train_trajectories
    return _load_trajectories("gentle_push_1000.hdf5", **dataset_args)
  File "/media/4TB_hardisk/sangam/HighMMT/datasets/gentle_push/data_loader.py", line 247, in _load_trajectories
    with fannypack.data.TrajectoriesFile(
  File "/home/sangam/anaconda3/envs/jtsaw/lib/python3.10/site-packages/fannypack/data/_trajectories_file.py", line 77, in __init__
    with self._h5py_file() as f:
  File "/home/sangam/anaconda3/envs/jtsaw/lib/python3.10/site-packages/fannypack/data/_trajectories_file.py", line 354, in _h5py_file
    return h5py.File(self._path, mode=mode, libver="latest")
  File "/home/sangam/anaconda3/envs/jtsaw/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/sangam/anaconda3/envs/jtsaw/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
```

**Comment by lvyiwei1** [comment]
Hi chinge55, thank you for your interest in our work! According to https://stackoverflow.com/questions/70344059/oserror-unable-to-open-file-file-signature-not-found , it seems like this error is likely caused by not downloading the data file or the data file is corrupted. Can you verify whether the data files you downloaded are correct and uncorrupted?

**Comment by chinge55** [comment]
@lvyiwei1  thank you for your quick response. 

In my case, while trying to run like above, the line below is where I get my error: File ```roboticstasks.py```, line 30.
```python
trains3, valid3, test3 = PushTask.get_dataloader(
    16, batch_size=18, drop_last=True, test_multimodal_only=True, test_noises=[0]
)
```
This leads to: In line 84 of ```get_dataloader.py```
```python
    def get_dataloader(
        cls, subsequence_length: int, modalities=None, test_multimodal_only=False,
        batch_size=32, drop_last=True, test_noises=range(10), train_sampler=None, **dataset_args
    ):
        # Load trajectories into memory
        train_trajectories = cls.get_train_trajectories(**dataset_args) 
       # Normal Code below
```
The variable ```dataset_args``` is empty

Leading to ```_load_trajectories()``` in data_loader.py line 189:
```python
      # Load trajectories file into memory, all at once
      with fannypack.data.TrajectoriesFile(
          fannypack.data.cached_drive_file(name, dataset_urls[name]) # Where I get ERROR!
      ) as f:
          raw_trajectories = list(f)
```
At the time of error: 
```python
name = 'gentle_push_1000.hdf5'
dataset_urls[name] = 'https://drive.google.com/file/d/1JTgmq1KPRK9HYi8BgvljKg5MPqT_N4cR/view?usp=sharing'
```

Should I download the data files separately, or will it be downloaded from google drive; the file ```gentle_push_1000.hdf5```?

As for robotics dataset, I've downloaded and extracted it in: ```datasets/robotics/triangle_real_data```

**Comment by lvyiwei1** [comment]
I think the error is probably due to the file not being downloaded correctly. 

Can you check if your `datasets/gentle_push/cache/1JTgmq1KPRK9HYi8BgvljKg5MPqT_N4cR-gentle_push_1000.hdf5` file is 500MB or 2KB? If it is 2KB, then you can fix it by downloading and replacing the file with the following commands:

```
gdown https://drive.google.com/uc?id=1JTgmq1KPRK9HYi8BgvljKg5MPqT_N4cR
mv gentle_push_1000.hdf5 datasets/gentle_push/cache/1JTgmq1KPRK9HYi8BgvljKg5MPqT_N4cR-gentle_push_1000.hdf5
```
