### ISSUE TITLE
Output will be model.pt

### ISSUE THREAD

**Issue by Gust-simon** [pliang279/HighMMT#5]
Hello, when the model encounters an error during training: Traceback (most recent call last):
File "private_test_scripts/perceivers/roboticstasks.py", line 198, in <module>
train(model,100,[trains3, trains4],[valid3, valid4],[test3, test4],
File "/home/pod/shared-nvme/HighMMT-main/private_test_scripts/perceivers/train_structure_multitask_robotics.py", line 58, in train
out = model(indict, modality_instance_mapping=modality_instance_mapping)#modality_instance_mapping=None
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
TypeError: Forward() got an unexpected keyword argument 'modality_instance mapping' causing the model to fail to train.Then, when I say 'out=model (indirect, After changing 'modality_instance_mapping' to 'out=model (indirect, None)', it got stuck in a loop.
![1](https://github.com/user-attachments/assets/3af2b3f1-ea52-4fe8-b476-7f0cc55f4db5)

**Comment by lvyiwei1** [comment]
I apologize for the `modality_instance_mapping` problem. I think the most recent commit should fix it. Thank you for reporting this!
