### ISSUE TITLE
No such file or directory: 'model. pt'.

### ISSUE THREAD

**Issue by Gust-simon** [pliang279/HighMMT#6]
Hello, when I run it, an error message appears: FileNotFoundError: [Errno 2] No such file or directory: 'model. pt'.

**Comment by lvyiwei1** [comment]
Can you provide more details about the problem? Which file are you running? What is the full printed stack trace of the error message?

**Comment by Gust-simon** [comment]
When I run "./run. sh tasks robots", the error "Traceback (most recent call last):
File "private_test_scripts/perceivers/roboticstasks.py", line 199, in <module>
train(model,100,[trains3, trains4],[valid3, valid4],[test3, test4],
File "/home/pod/shared-nvme/HighMMT-main/private_test_scripts/perceivers/train_structure_multitask_robotics.py", line 130, in train
model=torch.load(savedir,weights_only=True).to(device)
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/serialization.py", line 1065, in load
with _open_file_like(f, 'rb') as opened_file:
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/serialization.py", line 468, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/serialization.py", line 449, in __init__
super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model.pt'the file can be loaded successfully before this.
![2](https://github.com/user-attachments/assets/336ac7d7-bf37-4083-b3cf-e5e2d1ab9322)

**Comment by Gust-simon** [comment]
> 您能否提供有关此问题的更多详细信息？您正在运行的是哪个文件？错误消息的完整打印堆栈跟踪是什么？
When I run "./run. sh tasks robots", the error "Traceback (most recent call last):
File "private_test_scripts/perceivers/roboticstasks.py", line 199, in <module>
train(model,100,[trains3, trains4],[valid3, valid4],[test3, test4],
File "/home/pod/shared-nvme/HighMMT-main/private_test_scripts/perceivers/train_structure_multitask_robotics.py", line 130, in train
model=torch.load(savedir,weights_only=True).to(device)
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/serialization.py", line 1065, in load
with _open_file_like(f, 'rb') as opened_file:
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/serialization.py", line 468, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/home/pod/shared-nvme/miniconda3/envs/jtsaw/lib/python3.8/site-packages/torch/serialization.py", line 449, in __init__
super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model.pt'the file can be loaded successfully before this.
![2](https://github.com/user-attachments/assets/3a122de8-ee82-4e4b-b703-9d356f11253f)

**Comment by lvyiwei1** [comment]
I apologize for the problem. It seems like somehow the main training loop within `train_structure_multitask_robotics.py` was commented out for some reason. I have fixed it. It should be fixed with the newest commit.
